#pragma config(Sensor, dgtl1,  re,             sensorQuadEncoder)
#pragma config(Sensor, dgtl6,  le,             sensorQuadEncoder)
#pragma config(Motor,  port1,           fr,            tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           ml,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           bl,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           p2,            tmotorNone, openLoop)
#pragma config(Motor,  port5,           in,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           p1,            tmotorNone, openLoop)
#pragma config(Motor,  port8,           fl,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           mr,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          br,            tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


void forward()
{
	motor[fr]=127;
	motor[mr]=127;
	motor[br]=127;
	motor[fl]=127;
	motor[ml]=127;
	motor[bl]=127;
}

task main()
{
	while(SensorValue[re] > 360)
	{
		forward();
	}




}
